// FILE: data.ts
// PURPOSE: Compact derived mirror of the Foundation Section 8 B2
//          static entitlement catalog for the Control Tower
//          /billing read-only preview. All content is derived
//          verbatim from Foundation docs/entitlement-catalog/*.json
//          (Foundation PR #179 HEAD 308486c). NEVER live billing.
//          NEVER live payment. NEVER live entitlement enforcement.
//          NEVER live feature gating. NEVER activates anything.
//
// CANONICAL DOCTRINE (preserved verbatim):
//   "Billing is not just payment. Billing is the entitlement layer
//    that controls how Otzar's governed intelligence capabilities
//    scale across an enterprise."
//   "The DMW is not a luxury add-on. The Memory Wallet is
//    foundational trust infrastructure."
//   "Customers should not pay extra just to have memory be safe."
//   "Base Otzar must include enough DMW capability for every
//    Digital Twin to remember safely."
//   "Advanced memory governance can be premium; basic memory safety
//    cannot."
//   "Billing says what the organization has purchased. Governance
//    says what the system may safely do."
//   "Billing may entitle a connector pack; governance still
//    authorizes connector activation."
//   "Downgrades may disable new premium actions but must never
//    delete audit history, violate retention, or break evidence
//    integrity."
//
// CONNECTS TO: src/pages/BillingPreview.tsx,
//              src/lib/entitlement-catalog/types.ts.
// FOUNDATION SOURCE: docs/entitlement-catalog/{plans, seats,
//   capability-packs, connector-pack-families, usage-meters,
//   governance-rules, downgrade-policies, enterprise-add-ons}.json
//   + catalog.schema.json + README.md.

import type { EntitlementCatalogMirror } from "./types";

export const ENTITLEMENT_CATALOG_MIRROR: EntitlementCatalogMirror = {
  source_doctrine: [
    "Billing is not just payment. Billing is the entitlement layer that controls how Otzar's governed intelligence capabilities scale across an enterprise.",
    "The DMW is not a luxury add-on. The Memory Wallet is foundational trust infrastructure.",
    "Customers should not pay extra just to have memory be safe.",
    "Base Otzar must include enough DMW capability for every Digital Twin to remember safely.",
    "Advanced memory governance can be premium; basic memory safety cannot.",
    "Billing says what the organization has purchased. Governance says what the system may safely do.",
    "Billing may entitle a connector pack; governance still authorizes connector activation.",
    "Downgrades may disable new premium actions but must never delete audit history, violate retention, or break evidence integrity.",
  ],
  base_platform: {
    base_price_anchor: "$250/month base",
    base_includes: [
      "DMW baseline included",
      "Control Tower foundation access",
      "Dandelion Preview / basic seeding",
      "Baseline audit / security / governance",
      "Section 7 audit viewer + verify-chain",
      "Section 9 Approvals + Policies",
    ],
    base_excludes_at_starter_pilot: [
      "No advanced connector writes by default",
      "No executed workflow runtime in B2",
      "No payment provider runtime in B2",
      "No premium DMW governance",
      "No enterprise evidence pack",
      "No SSO / SAML / SCIM",
    ],
  },
  counts: {
    plans: 4,
    seats: 6,
    capability_packs: 9,
    connector_pack_families: 8,
    usage_meters: 16,
    governance_rules: 18,
    non_paywallable_safety_rules: 13,
    downgrade_policies: 5,
    enterprise_add_ons: 13,
  },
  plans: [
    {
      plan_id: "starter-pilot",
      name: "Starter / Pilot",
      target_customer: "Pilot teams, evaluation deployments, small orgs",
      base_summary: "$250 base + Dandelion Preview + baseline Admin Twin guidance + baseline audit + baseline DMW + limited workflow recommendations.",
      included_base_features: [
        "DMW baseline",
        "Audit baseline",
        "Foundation safety baseline",
        "Dandelion Preview",
        "Admin Twin baseline guidance when built",
      ],
      included_seat_types: ["Standard Digital Twin", "Otzar Administrator"],
      included_capability_packs: [],
      excluded_features: [
        "Advanced connector writes",
        "Executed workflow runtime",
        "Premium DMW governance",
        "Enterprise evidence pack",
        "SSO / SAML / SCIM",
      ],
      upgrade_path: "Starter / Pilot → Team → Business → Enterprise",
      downgrade_behavior: "Audit + DMW + safety baseline preserved per downgrade policy.",
      DMW_baseline_included: true,
      safety_baseline_included: true,
      audit_baseline_included: true,
    },
    {
      plan_id: "team",
      name: "Team",
      target_customer: "Departments + small / mid teams",
      base_summary: "$250 base + per-seat. Standard / Professional Twin seats. Collaboration Pack candidate. Basic workflow recommendations.",
      included_base_features: [
        "DMW baseline",
        "Audit baseline",
        "Foundation safety baseline",
        "Dandelion Preview",
        "Basic workflow recommendations",
      ],
      included_seat_types: ["Standard Digital Twin", "Professional Digital Twin", "Otzar Administrator"],
      included_capability_packs: ["Collaboration Pack candidate"],
      excluded_features: [
        "Executed workflow runtime in B2",
        "Premium DMW governance",
        "Enterprise evidence pack",
        "SSO / SAML / SCIM",
      ],
      upgrade_path: "Team → Business → Enterprise",
      downgrade_behavior: "Audit + DMW + safety baseline preserved; advanced features revoked.",
      DMW_baseline_included: true,
      safety_baseline_included: true,
      audit_baseline_included: true,
    },
    {
      plan_id: "business",
      name: "Business",
      target_customer: "Mid-market + growing enterprises",
      base_summary: "More seats. Admin Twin. Dandelion Activation Pack. Connector packs. Agent Playground. Advanced audit. Workflow recommendations / proposed actions. DMW governance baseline + selected premium controls.",
      included_base_features: [
        "DMW baseline",
        "Audit baseline",
        "Foundation safety baseline",
        "Dandelion Activation Pack",
        "Admin Twin",
        "Agent Playground",
        "Advanced audit",
        "Workflow recommendations",
        "Proposed actions",
      ],
      included_seat_types: ["Standard Digital Twin", "Professional Digital Twin", "Executive Twin", "Otzar Administrator", "Board / Observer"],
      included_capability_packs: [
        "Dandelion Activation Pack",
        "Workflow Automation Pack",
        "Advanced Audit / Compliance Pack",
        "DMW / Memory Governance Pack",
        "Agent Playground / Simulation Pack",
      ],
      excluded_features: [
        "Custom retention",
        "Regulator evidence pack (full)",
        "SSO / SAML / SCIM baseline",
        "Private cloud / VPC",
      ],
      upgrade_path: "Business → Enterprise",
      downgrade_behavior: "New premium actions may stop; audit + DMW + safety preserved.",
      DMW_baseline_included: true,
      safety_baseline_included: true,
      audit_baseline_included: true,
    },
    {
      plan_id: "enterprise",
      name: "Enterprise",
      target_customer: "Enterprises + regulated industries + multi-region orgs",
      base_summary: "Custom annual. Executive + board seats. Advanced DMW governance. Regulated evidence pack. Custom connectors. SSO / SAML / SCIM. Custom retention. Premium support. SLA.",
      included_base_features: [
        "DMW baseline",
        "Audit baseline",
        "Foundation safety baseline",
        "Dandelion Activation Pack",
        "Admin Twin",
        "Agent Playground",
        "Advanced audit",
        "Advanced DMW governance",
        "Regulated evidence pack",
        "SSO / SAML / SCIM",
        "Custom retention extension",
        "SLA",
      ],
      included_seat_types: [
        "Standard Digital Twin",
        "Professional Digital Twin",
        "Executive Twin",
        "Otzar Administrator",
        "Board / Observer",
        "External Collaborator",
      ],
      included_capability_packs: [
        "Dandelion Activation Pack",
        "Workflow Automation Pack",
        "Advanced Audit / Compliance Pack",
        "DMW / Memory Governance Pack",
        "Agent Playground / Simulation Pack",
        "Enterprise Analytics Pack",
        "Regulator / Evidence Pack",
        "Premium Support / Onboarding Pack",
      ],
      excluded_features: [],
      upgrade_path: "Enterprise is terminal in this catalog",
      downgrade_behavior: "Audit + DMW + safety + legal hold preservation absolute.",
      DMW_baseline_included: true,
      safety_baseline_included: true,
      audit_baseline_included: true,
    },
  ],
  seats: [
    {
      seat_id: "standard-twin",
      name: "Standard Digital Twin Seat",
      target_roles: "General employee / individual contributor / most operational roles",
      suggested_internal_price_range: "$25-$49 / user / month",
      included_capabilities: ["Twin baseline", "DMW baseline", "Foundation safety baseline", "Audit baseline"],
      excluded_capabilities: ["Admin Twin privileges", "Executive delegation ceiling", "Board / Observer read surface"],
      governance_requirements: ["Read-first defaults", "Delegated writes only", "DMW scope discipline"],
      DMW_baseline_included: true,
    },
    {
      seat_id: "professional-twin",
      name: "Professional Digital Twin Seat",
      target_roles: "Product Manager / CTO / Engineering Manager / Account Executive / CSM",
      suggested_internal_price_range: "$75-$125 / user / month",
      included_capabilities: ["Twin baseline", "DMW baseline", "Richer capability pack access when entitled", "Foundation safety baseline", "Audit baseline"],
      excluded_capabilities: ["Admin Twin privileges", "Executive delegation ceiling", "Board / Observer read surface"],
      governance_requirements: ["Read-first defaults", "Delegated writes only", "DMW scope discipline"],
      DMW_baseline_included: true,
    },
    {
      seat_id: "executive-twin",
      name: "Executive / High-Authority Twin Seat",
      target_roles: "CEO / Founder / CTO / CMO / COO / CFO / CHRO / General Counsel",
      suggested_internal_price_range: "$150-$300 / user / month",
      included_capabilities: ["Twin baseline", "DMW baseline", "Executive delegation profile", "Foundation safety baseline", "Advanced audit", "Audit baseline"],
      excluded_capabilities: ["Admin Twin privileges (unless combined)", "Board / Observer read-only surface (unless separate seat)"],
      governance_requirements: ["Explicit delegation profile", "Scope parity with human", "DMW scope discipline", "Advanced audit"],
      DMW_baseline_included: true,
    },
    {
      seat_id: "otzar-administrator",
      name: "Otzar Administrator Seat",
      target_roles: "Otzar Administrator (first-class role per ADR-0080 Amendment 5)",
      suggested_internal_price_range: "$99-$199 / admin / month",
      included_capabilities: [
        "Admin Twin baseline",
        "DMW baseline",
        "Governance review surface",
        "Capability pack activation review",
        "Connector activation review",
        "Workflow promotion review",
        "Billing review",
      ],
      excluded_capabilities: ["Payment provider runtime in B2", "Runtime workflow execution in B2", "Raw employee inspection"],
      governance_requirements: ["Map-aware synthesis", "Dual-control for risky writes", "DMW scope discipline", "Advanced audit"],
      DMW_baseline_included: true,
    },
    {
      seat_id: "board-observer",
      name: "Board / Observer Seat",
      target_roles: "Board member / observer (read-only surface only)",
      suggested_internal_price_range: "$49-$149 / user / month",
      included_capabilities: ["Governed read-only views", "Executive summary views", "DMW baseline", "Audit baseline"],
      excluded_capabilities: ["Write actions", "Approval actions", "Raw audit log (unbounded)", "Raw employee inspection"],
      governance_requirements: ["Read-only enforcement", "Scope discipline", "Audit baseline"],
      DMW_baseline_included: true,
    },
    {
      seat_id: "external-collaborator",
      name: "External Collaborator / Limited Seat",
      target_roles: "Vendor / contractor / advisor / partner (engagement-scoped only)",
      suggested_internal_price_range: "Custom / limited",
      included_capabilities: ["Engagement-scoped views", "DMW baseline", "Audit baseline"],
      excluded_capabilities: ["Cross-engagement visibility", "Broad tenant access", "Raw audit log (unbounded)"],
      governance_requirements: ["Engagement scope enforcement", "No cross-engagement access", "Audit baseline"],
      DMW_baseline_included: true,
    },
  ],
  capability_packs: [
    {
      pack_id: "dandelion-activation",
      name: "Dandelion Activation Pack",
      description: "Activates the 6-stage Dandelion maturity flow (A Preview → F Activation) per ADR-0082 + Amendment 1 cartographer doctrine.",
      included_features: ["Dandelion Preview to Activation flow", "Map authorship substrate", "Cartographer admin review surface"],
      activation_requirements: ["Entitlement", "Admin policy approval", "Foundation governance authorization", "Per-region Map approval"],
      entitlement_does_not_authorize: ["Region activation", "Map mutation", "Raw employee inspection"],
    },
    {
      pack_id: "workflow-automation",
      name: "Workflow Automation Pack",
      description: "Per ADR-0081 5-stage workflow maturity. Entitles Stages 3-5 (proposed action → governed execution → continuous optimization). Stages 1-2 are baseline.",
      included_features: ["Proposed action stage", "Governed execution stage", "Continuous optimization stage"],
      activation_requirements: ["Entitlement", "Admin policy approval", "Foundation governance authorization", "Workflow purpose binding"],
      entitlement_does_not_authorize: ["Autonomous execution", "Execution without purpose binding"],
    },
    {
      pack_id: "advanced-audit-compliance",
      name: "Advanced Audit / Compliance Pack",
      description: "Cross-scope verify-chain + advanced audit views + evidence packaging + regulator view per ADR-0036 LawfulBasis when applicable. Baseline audit remains in every plan.",
      included_features: ["Cross-scope verify-chain", "Advanced audit views", "Evidence packaging", "Regulator view (LawfulBasis-gated)"],
      activation_requirements: ["Entitlement", "Admin policy approval", "Foundation governance authorization"],
      entitlement_does_not_authorize: ["Regulator compliance certification", "Audit history modification"],
    },
    {
      pack_id: "dmw-memory-governance",
      name: "DMW / Memory Governance Pack",
      description: "Advanced DMW governance (custom retention extensions, advanced scope rules, regulated deletion variants, capsule provenance, cross-org lawful-basis composition). Baseline DMW is in every plan, NOT in this pack.",
      included_features: [
        "Custom retention extensions",
        "Advanced scope rules",
        "Regulated deletion variants",
        "Capsule provenance views",
        "Cross-org lawful-basis composition",
      ],
      activation_requirements: ["Entitlement", "Admin policy approval", "Foundation governance authorization"],
      entitlement_does_not_authorize: ["Baseline DMW safety modification", "RULE 0 relaxation"],
    },
    {
      pack_id: "agent-playground-simulation",
      name: "Agent Playground / Simulation Pack",
      description: "Per ADR-0077 + Section 5 Wave 9/10. Multi-agent simulation orchestration + enterprise decision cockpit. Section 5 Foundation backend LIVE.",
      included_features: [
        "Multi-agent simulation",
        "Enterprise decision cockpit",
        "Scenario persistence",
        "Candidate generation",
        "Outcome comparison",
        "Best-path recommendation",
        "Governed transition",
      ],
      activation_requirements: ["Entitlement", "Admin policy approval"],
      entitlement_does_not_authorize: ["Autonomous execution from simulation"],
    },
    {
      pack_id: "enterprise-analytics",
      name: "Enterprise Analytics Pack",
      description: "Per ADR-0061 Section 6 Waves 6+7. Live aggregates (action-runtime health, compliance posture) at org tier. Metadata-only aggregates.",
      included_features: ["Action-runtime health aggregate", "Compliance posture aggregate", "Governed aggregate views"],
      activation_requirements: ["Entitlement", "Admin policy approval"],
      entitlement_does_not_authorize: ["Per-employee inspection"],
    },
    {
      pack_id: "regulator-evidence",
      name: "Regulator / Evidence Pack",
      description: "Regulator-ready evidence packaging per ADR-0070 + ADR-0036 LawfulBasis + ADR-0071 cross-scope verify-chain. Examination-ready substrate.",
      included_features: [
        "Regulator view (LawfulBasis-gated)",
        "Evidence package generation",
        "Cross-scope verify-chain",
        "Neutral compliance summary",
      ],
      activation_requirements: ["Entitlement", "Admin policy approval", "LawfulBasis when regulator access"],
      entitlement_does_not_authorize: ["Regulator certification claim"],
    },
    {
      pack_id: "premium-support-onboarding",
      name: "Premium Support / Onboarding Pack",
      description: "Premium support + premium onboarding services. Services entitlement (does not change product capability).",
      included_features: ["Premium support SLA", "Premium onboarding services", "Dedicated success management"],
      activation_requirements: ["Entitlement", "Admin policy approval"],
      entitlement_does_not_authorize: ["Cross-tenant visibility", "Governance override"],
    },
    {
      pack_id: "collaboration-pack-candidate",
      name: "Connector Pack (Collaboration candidate)",
      description: "Collaboration connector pack candidate for Team plan. Bundles Slack / Teams / Gmail / Outlook / Calendars per ADR-0084.",
      included_features: ["Slack candidate", "Teams candidate", "Gmail candidate", "Outlook candidate", "Google Calendar candidate", "Outlook Calendar candidate"],
      activation_requirements: [
        "Entitlement",
        "Admin policy approval",
        "Foundation governance authorization",
        "Per-region Map approval",
        "Per-connector RULE 21 research arc",
      ],
      entitlement_does_not_authorize: ["Connector activation"],
    },
  ],
  connector_pack_families: [
    {
      pack_id: "collaboration",
      name: "Collaboration Pack",
      vendors: ["Slack", "Microsoft Teams", "Gmail", "Outlook", "Google Calendar", "Outlook Calendar"],
      wave_6_first_connector_candidate: "Slack (Wave 6 score 16.00)",
      activation_requirements: [
        "Entitlement",
        "Admin policy approval",
        "Foundation governance authorization",
        "Per-region Map approval",
        "Per-connector RULE 21 research arc",
      ],
    },
    {
      pack_id: "workspace-knowledge",
      name: "Workspace / Knowledge Pack",
      vendors: ["Google Drive", "Google Docs", "Google Sheets", "Google Slides", "Microsoft 365", "SharePoint", "OneDrive", "Notion", "Confluence"],
      wave_6_first_connector_candidate: "Google Workspace (Wave 6 score 13.33)",
      activation_requirements: [
        "Entitlement",
        "Admin policy approval",
        "Foundation governance authorization",
        "Per-region Map approval",
        "Per-connector RULE 21 research arc",
      ],
    },
    {
      pack_id: "project-engineering",
      name: "Project / Engineering Pack",
      vendors: ["Jira", "Linear", "Asana", "Monday", "GitHub", "GitLab"],
      wave_6_first_connector_candidate: "Project Tracker (Wave 6 score 12.75)",
      activation_requirements: [
        "Entitlement",
        "Admin policy approval",
        "Foundation governance authorization",
        "Per-region Map approval",
        "Per-connector RULE 21 research arc",
      ],
    },
    {
      pack_id: "revenue",
      name: "Revenue Pack",
      vendors: ["Salesforce", "HubSpot", "Gong", "Outreach", "Salesloft"],
      activation_requirements: [
        "Entitlement",
        "Admin policy approval",
        "Foundation governance authorization",
        "Per-region Map approval",
        "Per-connector RULE 21 research arc",
      ],
    },
    {
      pack_id: "customer",
      name: "Customer Pack",
      vendors: ["Zendesk", "Intercom", "Gainsight", "ChurnZero"],
      activation_requirements: [
        "Entitlement",
        "Admin policy approval",
        "Foundation governance authorization",
        "Per-region Map approval",
        "Per-connector RULE 21 research arc",
      ],
    },
    {
      pack_id: "people",
      name: "People Pack",
      vendors: ["Workday", "BambooHR", "Rippling", "Greenhouse", "Lever", "Lattice"],
      activation_requirements: [
        "Entitlement",
        "Admin policy approval",
        "Foundation governance authorization",
        "Per-region Map approval",
        "Per-connector RULE 21 research arc",
      ],
    },
    {
      pack_id: "finance-expense-travel",
      name: "Finance / Expense / Travel Pack",
      vendors: ["SAP Concur", "Ramp", "Brex", "Expensify", "Navan / TripActions", "TravelPerk", "NetSuite", "QuickBooks", "Bill.com"],
      activation_requirements: [
        "Entitlement",
        "Admin policy approval",
        "Foundation governance authorization",
        "Per-region Map approval",
        "Per-connector RULE 21 research arc",
        "Dual-control for money-moving writes",
      ],
    },
    {
      pack_id: "legal-compliance",
      name: "Legal / Compliance Pack",
      vendors: ["DocuSign", "Ironclad", "Vanta", "Drata", "OneTrust"],
      activation_requirements: [
        "Entitlement",
        "Admin policy approval",
        "Foundation governance authorization",
        "Per-region Map approval",
        "Per-connector RULE 21 research arc",
        "Dual-control for legal-effect writes",
      ],
    },
  ],
  usage_meters: [
    { meter_id: "active-twin-seats", name: "Active Digital Twin Seats", unit: "seat-month", counted_event: "Seat assignment active during the billing period", enforcement_mode: "Deferred to B3+" },
    { meter_id: "active-admin-seats", name: "Active Admin Seats", unit: "admin-seat-month", counted_event: "Admin seat assignment active during the billing period", enforcement_mode: "Deferred to B3+" },
    { meter_id: "active-board-observer-seats", name: "Active Board / Observer Seats", unit: "observer-seat-month", counted_event: "Observer seat assignment active during the billing period", enforcement_mode: "Deferred to B3+" },
    { meter_id: "dandelion-activation-runs", name: "Dandelion Activation Runs", unit: "activation-run", counted_event: "Approved Dandelion activation run", enforcement_mode: "Deferred to B3+" },
    { meter_id: "workflow-recommendations", name: "Workflow Recommendations", unit: "recommendation", counted_event: "Workflow recommendation surfaced", enforcement_mode: "Deferred to B3+" },
    { meter_id: "workflow-runs", name: "Workflow Runs", unit: "run", counted_event: "Governed workflow execution", enforcement_mode: "Deferred to B3+" },
    { meter_id: "proposed-actions", name: "Proposed Actions", unit: "proposed-action", counted_event: "Proposed Action recorded", enforcement_mode: "Deferred to B3+" },
    { meter_id: "connector-read-events", name: "Connector Read Events", unit: "read-event", counted_event: "Connector read event", enforcement_mode: "Deferred to B3+" },
    { meter_id: "connector-write-events", name: "Connector Write Events", unit: "write-event", counted_event: "Approved connector write event", enforcement_mode: "Deferred to B3+" },
    { meter_id: "simulation-runs", name: "Simulation Runs", unit: "simulation-run", counted_event: "Agent Playground simulation run", enforcement_mode: "Deferred to B3+" },
    { meter_id: "audit-exports", name: "Audit Exports", unit: "export-op", counted_event: "Audit export operation", enforcement_mode: "Deferred to B3+" },
    { meter_id: "evidence-package-generation", name: "Evidence Package Generation", unit: "evidence-package", counted_event: "Regulator evidence package generated", enforcement_mode: "Deferred to B3+" },
    { meter_id: "memory-capsule-volume", name: "Memory Capsule Volume", unit: "capsule-count or storage-bytes", counted_event: "Capsule storage volume", enforcement_mode: "Deferred to B3+" },
    { meter_id: "advanced-dmw-governance-events", name: "Advanced DMW Governance Events", unit: "event", counted_event: "Advanced DMW governance event", enforcement_mode: "Deferred to B3+" },
    { meter_id: "high-volume-listener-transcript-processing", name: "High-volume Listener / Transcript Processing", unit: "processing-event", counted_event: "Transcript processing event (forward-substrate)", enforcement_mode: "Deferred to listener landing + B3+" },
    { meter_id: "external-api-calls", name: "External API Calls", unit: "api-call", counted_event: "External API call (forward-substrate)", enforcement_mode: "Deferred to external-API landing + B3+" },
  ],
  governance_rules: [
    { id: "rule.entitlement-is-not-authority.v1", name: "Entitlement is not authority", human_readable_summary: "Billing says what the organization has purchased. Governance says what the system may safely do." },
    { id: "rule.billing-does-not-override-foundation-governance.v1", name: "Billing does not override Foundation governance", human_readable_summary: "Foundation governance is absolute. Premium plans do not buy governance relaxation." },
    { id: "rule.connector-pack-does-not-activate-connector.v1", name: "Connector pack does not activate connector", human_readable_summary: "Billing may entitle a connector pack; governance still authorizes connector activation." },
    { id: "rule.workflow-pack-does-not-authorize-execution.v1", name: "Workflow pack does not authorize execution", human_readable_summary: "Workflow execution always governance-bound." },
    { id: "rule.dmw-baseline-included-for-trust.v1", name: "DMW baseline included for trust", human_readable_summary: "The DMW is not a luxury add-on. The Memory Wallet is foundational trust infrastructure." },
    { id: "rule.advanced-dmw-governance-premium-not-basic-safety.v1", name: "Advanced DMW governance is premium, not basic safety", human_readable_summary: "Advanced memory governance can be premium; basic memory safety cannot." },
    { id: "rule.downgrade-preserves-audit-and-retention.v1", name: "Downgrade preserves audit and retention", human_readable_summary: "Downgrades may disable new premium actions but must never delete audit history, violate retention, or break evidence integrity." },
    { id: "rule.non-payment-disables-new-premium-actions-only.v1", name: "Non-payment disables new premium actions only", human_readable_summary: "Non-payment pauses new premium actions only; never erases history or breaks safety." },
    { id: "rule.basic-security-not-unsafe-paywalled.v1", name: "Basic security is not unsafe paywalled", human_readable_summary: "Foundation security baseline is included in every plan." },
    { id: "rule.same-org-boundary-never-weakened.v1", name: "Same-org boundary is never weakened", human_readable_summary: "Cross-tenant boundary is absolute regardless of plan tier or commercial pressure." },
    { id: "rule.map-region-approval-required.v1", name: "Map-region approval required", human_readable_summary: "Dandelion maps the territory; admins approve the map; Foundation governs what can happen inside the map." },
    { id: "rule.admin-policy-approval-required-for-activation.v1", name: "Admin policy approval required for activation", human_readable_summary: "Activation requires admin policy approval. Never autonomous activation." },
    { id: "rule.dual-control-for-risky-writes.v1", name: "Dual-control for risky writes", human_readable_summary: "Risky writes (money-moving, legal-effect, governance-modifying) require dual-control regardless of plan tier." },
    { id: "rule.no-employee-scoring.v1", name: "No workforce-scoring inferences", human_readable_summary: "No plan / pack / connector / capability surfaces workforce-scoring inferences of any kind. Forbidden inference." },
    { id: "rule.no-manager-surveillance.v1", name: "No managerial-oversight monitoring", human_readable_summary: "No plan / pack / connector / capability surfaces managerial-oversight monitoring of individual workers. Forbidden inference." },
    { id: "rule.no-sensitive-attribute-inference.v1", name: "No sensitive-attribute inference", human_readable_summary: "No plan / pack / connector / capability surfaces sensitive-attribute inference. Forbidden inference." },
    { id: "rule.no-regulator-approval-claims.v1", name: "No regulatory-approval claims", human_readable_summary: "Never claim regulatory approval, guaranteed compliance, or absence of regulatory fine risk." },
    { id: "rule.no-guaranteed-compliance-claims.v1", name: "No guaranteed compliance claims", human_readable_summary: "Never claim guaranteed compliance for any plan / pack / capability." },
  ],
  non_paywallable_safety_rules: [
    { id: "non-paywallable.historical-audit-records.v1", name: "Historical audit records", human_readable_summary: "Historical audit records are never deleted, paywalled, or reduced by downgrade." },
    { id: "non-paywallable.legally-required-retention.v1", name: "Legally required retention", human_readable_summary: "Legal retention is never reduced by commercial events." },
    { id: "non-paywallable.audit-chain-integrity.v1", name: "Audit chain integrity", human_readable_summary: "Audit chain integrity is absolute and never paywalled." },
    { id: "non-paywallable.basic-dmw-memory-safety.v1", name: "Basic DMW memory safety", human_readable_summary: "Basic memory safety is never paywalled." },
    { id: "non-paywallable.basic-security-controls.v1", name: "Basic security controls", human_readable_summary: "Foundation security baseline is never paywalled." },
    { id: "non-paywallable.user-offboarding-safety.v1", name: "User offboarding safety", human_readable_summary: "User offboarding never breaks safety." },
    { id: "non-paywallable.ability-to-disconnect-or-revoke-connectors.v1", name: "Ability to disconnect or revoke connectors", human_readable_summary: "Connector disconnect / revoke is never paywalled." },
    { id: "non-paywallable.compliance-audit-export-during-grace-or-legal-window.v1", name: "Compliance / audit export during grace or legal window", human_readable_summary: "Legal-window audit export is never paywalled." },
    { id: "non-paywallable.ability-to-disable-risky-automation-or-connectors.v1", name: "Ability to disable risky automation or connectors", human_readable_summary: "Admin kill-switch is never paywalled." },
    { id: "non-paywallable.preserving-data-boundaries.v1", name: "Preserving data boundaries", human_readable_summary: "Data boundaries are absolute." },
    { id: "non-paywallable.same-org-boundary.v1", name: "Same-org boundary", human_readable_summary: "Same-org boundary is absolute." },
    { id: "non-paywallable.cross-tenant-isolation.v1", name: "Cross-tenant isolation", human_readable_summary: "Cross-tenant isolation is absolute." },
    { id: "non-paywallable.legal-hold-preservation.v1", name: "Legal hold preservation", human_readable_summary: "Legal hold is never broken by commercial events." },
  ],
  downgrade_policies: [
    {
      policy_id: "upgrade",
      name: "Upgrade Policy",
      human_readable_summary: "Upgrade adds entitlement. Activation still requires Foundation governance approval. Existing audit + DMW + safety baseline preserved.",
      preserved_invariants: ["Audit", "Evidence", "Legal retention", "DMW safety", "Historical records", "Export window", "Connector disconnection safety", "Same-org boundaries", "Lawful window"],
    },
    {
      policy_id: "downgrade",
      name: "Downgrade Policy",
      human_readable_summary: "Downgrades may disable new premium actions but must never delete audit history, violate retention, or break evidence integrity.",
      preserved_invariants: ["Audit", "Evidence", "Legal retention", "DMW safety", "Historical records", "Export window", "Connector disconnection safety", "Same-org boundaries", "Lawful window"],
    },
    {
      policy_id: "non-payment-grace",
      name: "Non-Payment Grace Policy",
      human_readable_summary: "Non-payment pauses new premium actions only; preserves data + audit + DMW safety + legal-window exports.",
      preserved_invariants: ["Audit", "Evidence", "Legal retention", "DMW safety", "Historical records", "Export window", "Connector disconnection safety", "Same-org boundaries", "Lawful window"],
    },
    {
      policy_id: "cancellation",
      name: "Cancellation Policy",
      human_readable_summary: "Cancellation ends commercial relationship; preserves lawful retention window + legal hold + audit + DMW safety.",
      preserved_invariants: ["Audit", "Evidence", "Legal retention", "DMW safety", "Historical records", "Export window", "Connector disconnection safety", "Same-org boundaries", "Lawful window"],
    },
    {
      policy_id: "enterprise-contract-end",
      name: "Enterprise Contract End Policy",
      human_readable_summary: "Enterprise contract end. Negotiated transition. Preserves all safety invariants.",
      preserved_invariants: ["Audit", "Evidence", "Legal retention", "DMW safety", "Historical records", "Export window", "Connector disconnection safety", "Same-org boundaries", "Lawful window"],
    },
  ],
  enterprise_add_ons: [
    { id: "addon.sso-saml-scim.v1", name: "SSO / SAML / SCIM", description: "Enterprise SSO + SAML + SCIM provisioning. Per-tenant secret isolation." },
    { id: "addon.custom-retention.v1", name: "Custom Retention", description: "Custom retention extension above lawful retention floor. Extends; never reduces." },
    { id: "addon.custom-connector.v1", name: "Custom Connector", description: "Custom connector adapter for enterprise-specific vendor systems. Per-connector RULE 21 research arc per ADR-0084." },
    { id: "addon.advanced-dmw-policy.v1", name: "Advanced DMW Policy", description: "Advanced DMW policy add-on. Extends DMW Memory Governance pack." },
    { id: "addon.private-cloud-vpc.v1", name: "Private Cloud / VPC", description: "Private cloud / VPC deployment add-on per ADR-0018 deployment-target agnosticism." },
    { id: "addon.regulated-deployment.v1", name: "Regulated Deployment", description: "Regulated industry deployment (sovereign cloud, FedRAMP-aligned posture)." },
    { id: "addon.dedicated-support.v1", name: "Dedicated Support", description: "Dedicated support engineer / customer success management." },
    { id: "addon.sla.v1", name: "SLA", description: "Service-level agreement add-on with uptime + response-time + remediation commitments." },
    { id: "addon.dpa-msa.v1", name: "DPA / MSA", description: "Data processing agreement + master services agreement add-on." },
    { id: "addon.premium-onboarding.v1", name: "Premium Onboarding", description: "Premium onboarding services for enterprise activation. Dandelion-aligned." },
    { id: "addon.custom-evidence-workflows.v1", name: "Custom Evidence Workflows", description: "Custom evidence-packaging workflows for regulator-ready enterprise." },
    { id: "addon.audit-export-expansion.v1", name: "Audit Export Expansion", description: "Audit export expansion above per-plan inclusion. Baseline + legal window exports remain non-paywallable." },
    { id: "addon.security-review-package.v1", name: "Security Review Package", description: "Security review package for enterprises requiring formal security review documentation." },
  ],
  billing_admin_permission_profile: {
    id: "permission-profile.billing-admin.v1",
    name: "Billing Admin Permission Profile",
    description: "Billing Admin role profile per ADR-0083 Amendment 1 §9.7. Owns commercial state. Never overrides Foundation governance, connector activation, workflow execution, or DMW policy.",
    safe_defaults: [
      "Commercial state management",
      "Plan tier management",
      "Seat management",
      "Pack entitlement management",
      "Usage review",
      "Billing audit review",
    ],
    forbidden_defaults: [
      "Connector activation authority",
      "Workflow execution authority",
      "DMW policy modification",
      "Governance override",
      "Audit history modification",
    ],
  },
  forbidden_inferences: [
    "No workforce-scoring inferences",
    "No managerial-oversight monitoring",
    "No sensitive-attribute inference",
    "No personality-trait inference",
    "No regulatory-approval claims",
    "No guaranteed-compliance claims",
  ],
  preview_disclaimers: [
    "This preview does not charge customers, activate billing, gate features, or connect payment providers.",
    "Capability packs entitle availability; they do not authorize activation.",
    "Connector packs are not live connectors.",
    "Suggested internal price ranges are anchors, not contractual or final public pricing.",
    "Foundation governance authorizes every activation regardless of plan tier.",
  ],
};
